### ISSUE TITLE
fetch_feeds.py - TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by suminb** [suminb/secondary-brain#7]
```
Traceback (most recent call last):
  File "bin/fetch_feeds.py", line 117, in <module>
    fetch_feed_items()
  File "bin/fetch_feeds.py", line 82, in fetch_feed_items
    db.session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 719, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 352, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 332, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1814, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1896, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 525, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 53, in save_obj
    table, states_to_update)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 331, in _collect_update_commands
    attributes.PASSIVE_NO_INITIALIZE)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1385, in get_state_history
    return state.get_history(key, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 206, in get_history
    return self.manager[key].impl.get_history(self, self.dict, passive)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 695, in get_history
    self, state, dict_.get(self.key, NO_VALUE))
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1278, in from_scalar_attribute
    elif attribute.is_equal(current, original) is True:
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/types.py", line 203, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by suminb** [comment]
`fetch_feeds.py` will be no longer in use.
